### ISSUE TITLE
Any plan to release the whole model?

### ISSUE THREAD

**Issue by UMGrain** [mapooon/BlendFace#1]
Hi, great work! I wanna know whether you will release the whole model(BlendFace + face-swapping model).

**Comment by cute23333** [comment]
Me too. I'm willing for a pytorch model. I really want to apply it to other projects.

**Comment by mapooon** [comment]
Hi,
We are currently on deadlines for other works, so it is taking some time to release the scripts.
We will release them by the conference. 
Thank you for your understanding.

**Comment by zimenglan-sysu-512** [comment]
hi @mapooon 
can u release more model, e.g r18/34/50 ?

**Comment by mapooon** [comment]
Code and model have been released.

**Comment by mapooon** [comment]
@zimenglan-sysu-512 
Unfortunately, there is no plan to release other pretrained backbones at this time.

**Comment by zimenglan-sysu-512** [comment]
ok thanks
