### ISSUE TITLE
Can this encoder be applied to StyleGAN?

### ISSUE THREAD

**Issue by jianmanLin** [mapooon/BlendFace#3]
Hello author, thank you for your sharing, can the proposed encoder be applied to StyleGAN?

**Comment by mapooon** [comment]
Hi,
I think yes.
For example, [ShapeEditor](https://arxiv.org/abs/2106.13984.pdf) performs face-swapping using pretrained StyleGAN and ArcFace identity encoder. 
You can replace ArcFace with our BlendFace in the method.
