### ISSUE TITLE
how face swap

### ISSUE THREAD

**Issue by loboere** [mapooon/BlendFace#4]
great work but where face swap code

**Comment by mapooon** [comment]
Hi,
We are currently on deadlines for other works, so it is taking some time to release the scripts.
We will release them by the conference. 
Thank you for your understanding.

**Comment by arnold408** [comment]
Hi, please release face swap code and model. Thanks

**Comment by mapooon** [comment]
Code and model have been released.

**Comment by loboere** [comment]
some way to crop and align faces, that's where the swap seems to go wrong
