### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by lizian1611** [mapooon/BlendFace#6]
Figure 9 in your paper visualizes the images of ArcFace and BleedFace. If convenient, could you please provide some details? I really appreciate my interest in this aspect, thank you!

**Comment by mapooon** [comment]
Sorry for the late reply.

We conduct the following procedure:
1. We compute identity similarity between input and reference. Let this score be _a_.
2. We mask a region of the input and compute identity similarity to reference. Let this score be _a_. This measures the importance of the masked region in terms of identity. We define the importance as _a-b_.
3. We slide the masked region and compute id sim in the same manner as step 2. We iterate this process for all the regions of the input.
4. We change the mask size and do step 2 and 3. We adopt sizes of {16, 24, 32, 40, 48, 56}.
5. We average the importance for all the regions over the masks and visualize it as a heatmap in figure 9.
