### ISSUE TITLE
how to train ?

### ISSUE THREAD

**Issue by salisbury-espinosa** [mapooon/BlendFace#7]

**Comment by mapooon** [comment]
Unfortunately, we have no plan to release training code for face-swapping.
Our face-swapping code is based mainly on a third party implementation of AEI-Net ([here](https://github.com/maum-ai/faceshifter)).

**Comment by mapooon** [comment]
Yes, we will release training code for BlendFace (identity encoder).

**Comment by zimenglan-sysu-512** [comment]
hi @mapooon when will release the train code of BlendFace?

**Comment by mapooon** [comment]
Training code has been released.
