### ISSUE TITLE
Bad swap results

### ISSUE THREAD

**Issue by HeChengHui** [mapooon/BlendFace#9]
@mapooon 
Thank you for your work. 
I have been testing out your face swap model and the results seems to be quite bad.

steps taken:
1) download blendswap.pth
2) use insightface detector and face_align in their utils on both source and target
3) change target to (256, 256) when converting to tensor
4) result (supposed to be emma on cage lol)
![output](https://github.com/mapooon/BlendFace/assets/84503515/a5209c1d-e7c9-4f41-a489-38041cbbc2e6)

Any advice on how to make it work properly?

**Comment by mapooon** [comment]
Hi, 
Target images should be aligned in FFHQ manner, as I mentioned in `README.md`.
[This](https://github.com/happy-jihye/FFHQ-Alignment) is a good code to align.
